### ISSUE TITLE
Svelte 5: afterNavigate doesn't run after opening a page

### ISSUE THREAD

**Issue by amit13k** [sveltejs/kit#11778]
### Describe the bug

afterNavigate doesn't seem to run after component mounts when using Svelte 5 with Svelte Kit.

### Reproduction

[Svelte 5 + Svelte Kit issue](https://www.sveltelab.dev/c0hivjda61z75jo)
[Svelte 4 + Svelte Kit works fine](https://www.sveltelab.dev/z292bvnu2w00b2e)

### System Info

```Shell
System:
    OS: macOS 14.3
    CPU: (12) arm64 Apple M2 Pro
    Memory: 721.33 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - /opt/homebrew/bin/npm
    pnpm: 8.11.0 - ~/Library/pnpm/pnpm
    bun: 1.0.25 - ~/.bun/bin/bun
  Browsers:
    Chrome: 121.0.6167.139
    Chrome Canary: 123.0.6274.0
    Safari: 17.3
```

### Severity

blocking an upgrade

**Comment by dummdidumm** [comment]
I noticed this as well when doing a test migration of learn.svelte.dev. it happens because onmount runs too late in the root. This probably needs a change in SvelteKit

**Comment by pheuter** [comment]
@dummdidumm Could this be related to #11775?

**Comment by dummdidumm** [comment]
This has been fixed

**Comment by janosh** [comment]
i'm still seeing this issue with `"svelte": "5.19.2"` and `"@sveltejs/kit": "^2.16.1"`. neither `onMount` nor `afterNavigate` actually fire on page load

**Comment by Crenshinibon** [comment]
Me too. Did you find the reason for this behaviour?
