### ISSUE TITLE
SvelteKit Dev Server Infinite Loading

### ISSUE THREAD

**Issue by IggyCeltic** [sveltejs/kit#12020]
### Describe the bug

When running the sveltekit application, the appllication running at `localhost:5173/` will infinitely load, even after all elements and network events have finished.

### Reproduction

https://github.com/IggyCeltic/bug-repro

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 9 7940HS w/ Radeon 780M Graphics
    Memory: 4.20 GB / 15.21 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.92)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-auto: ^3.1.1 => 3.1.1
    @sveltejs/adapter-cloudflare: ^4.2.0 => 4.2.0
    @sveltejs/kit: ^2.5.4 => 2.5.4
    @sveltejs/vite-plugin-svelte: ^3.0.2 => 3.0.2
    svelte: ^4.2.12 => 4.2.12
    vite: ^5.2.3 => 5.2.3
```

### Severity

serious, but I can work around it

### Additional Information

Prevents all hot loading. In order to get changes refreshed have to stop the load and refresh the page.

**Comment by knd775** [comment]
This issue started with vite 5.2.0, but only seems to affect (some) sveltekit users

**Comment by buhodev** [comment]
I had the same issue. It's vite's fault in my case. I downgraded to `v5.1.6` and everything worked.

**Comment by IggyCeltic** [comment]
It does look like downgrading to vite `5.1.6` might be fixing it for me as well.

**Comment by parskongar** [comment]
Downgrading to adapter-cloudflare `4.1.0` seems to be fixing it

**Comment by fredguest** [comment]
The relevant Vite issue -> https://github.com/vitejs/vite/issues/16245

**Comment by ZerdoX-x** [comment]
I spent several hours, this is the changes that caused the issue: https://github.com/vitejs/vite/pull/16135
Introduced in vite@5.2.0-beta.1
vite@5.2.0-beta.0 works fine

In my case vite breaks [@inlang/paraglide-js-adapter-sveltekit](https://www.npmjs.com/package/@inlang/paraglide-js-adapter-sveltekit), without it, in clean project, all works fine.

**Comment by arxpoetica** [comment]
I added a repro to the ticket: https://github.com/vitejs/vite/issues/16245#issuecomment-2016535216

**Comment by patak-dev** [comment]
Sorry for the regression, it will be fixed by https://github.com/vitejs/vite/pull/16246. I'll cut a release tomorrow

**Comment by gtm-nayan** [comment]
The fix has been released in Vite 5.2.5.

**Comment by gemue-parndt** [comment]
This is still happening sometimes without any reason.
Only works again after fully rebooting the computer ?!

**Comment by ZerdoX-x** [comment]
> Only works again after fully rebooting the computer ?!

Reinstall windows

**Comment by gemue-parndt** [comment]
It still happening even after a year wtf is this?
Only works if SSR is turned off...

**Comment by teemingc** [comment]
> It still happening even after a year wtf is this? Only works if SSR is turned off...

Please submit a new issue with a minimal reproduction. Otherwise, there's no way to diagnose and fix the issue.
