### ISSUE TITLE
Deterministic `version.name`

### ISSUE THREAD

**Issue by eltigerchino** [sveltejs/kit#14176]
### Describe the bug

See https://github.com/sveltejs/kit/pull/14166 for context.

Our documentation requires a deterministic value for the `version.name` config setting but does not warn the user if they have used something indeterministic. This can be very difficult to debug as the app version hash changes throughout the build and files won't match to correct payload accordingly.

Furthermore, our default value for the setting is based on the build time. However, nothing could have changed and the version name will still be different when re-running the build. This is indeterministic too.

Some ideas from Rich:
> I think it might be worth us investing some time to think about what it would mean to have a deterministic version automatically. For example: I haven't thought this all the way through but could we generate the version dynamically by hashing the inputs to Vite? Maybe we need to account for externalised server-side dependencies, in which case perhaps we need to account for a lockfile/package.json in addition. Or maybe even if the code hasn't changed, we need to account for any data that changed in prerendered content, in which case perhaps we use a placeholder value at first, compute the version after prerendering, and then replace the placeholder in any outputs in which it appeared?

### Reproduction

https://github.com/gageracer/sudokusu/pull/6#issuecomment-3173666829

### Logs

```Shell

```

### System Info

```Shell
-
```

### Severity

serious, but I can work around it

### Additional Information

-

**Comment by sirkostya009** [comment]
With Rolldown's improved determinism the issue with `version.name` being unique on each run is the only thing preventing back-to-back bundle builds being fully reproducible.

Using git HEAD commit sha is thankfully a viable option, but it still may be an issue in monorepo setups.

Consider dealing with this in SvelteKit 3.0?

> pinging just in case @teemingc

**Comment by dummdidumm** [comment]
There were two parts to this:
1. the svelte.config.js was loaded on each sub process (e.g. during prerendering), and a non-stable version.name is a problem here. This is fixed with SvelteKit 3 because we can reuse the vite config.
2. each version.name change affected all the SvelteKit runtime files, which only change if you update your SvelteKit version. This is fixed in SvelteKit 3, too, where we have adjusted files such that the version is no longer part of the file contents.

As such we can close this now, because we didn't really need a deterministic version.name, what we actually needed were the two things listed

**Comment by teemingc** [comment]
I was wrong about point 1. It probably still happens when we resolve the Vite config in the sub-processes. Don't think it affects anything though since we serialise the version to a file during build
