### ISSUE TITLE
Cannot access '' before initialization

### ISSUE THREAD

**Issue by AndreasHald** [sveltejs/kit#14679]
### Describe the bug

Build fails on a certain remote function setup.
```                           
ReferenceError [Error]: Cannot access 'schema' before initialization
    at file:///Users/hald/Documents/svelte-kit-remote-function-reproduction/.svelte-kit/output/server/chunks/remote-1e3r2ap.js:15:26
    at ModuleJob.run (node:internal/modules/esm/module_job:271:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:547:26)
    at async analyse (file:///Users/hald/Documents/svelte-kit-remote-function-reproduction/node_modules/@sveltejs/kit/src/core/postbuild/analyse.js:173:34)
    at async MessagePort.<anonymous> (file:///Users/hald/Documents/svelte-kit-remote-function-reproduction/node_modules/@sveltejs/kit/src/utils/fork.js:23:16)
```

The reproduction attempts to illustrate the setup as simply as possible but what we are doing on a high level is defining table columns using a const

```ts

export const tableSetup = {
   name: {
      cell: SomeComponent,
      type: 'text',
      facet: 'some-facet-type',
      sortable: true,
      ...
   }
}

```

And then inferring the schema for remote functions based on that
```ts

export const schema = buildSchemaFromTableSetup(tableSetup)

```

That way when calling remote functions, you can get types on your filtering, sorting and faceting of the table rows which is really nice.

However when updating to the latest version of SvelteKit building this fails. We are currently building it successfully on `2.38.1`

### Reproduction

https://github.com/21RISK/sveltekit-remote-function-reproduction

reproduction created from `npx sv create` with as minimal changes as possible to highlight issue. run `npm run build` to see error

### Logs

```Shell
node:internal/event_target:1101
  process.nextTick(() => { throw err; });
                           ^
ReferenceError [Error]: Cannot access 'schema' before initialization
    at file:///Users/hald/Documents/svelte-kit-remote-function-reproduction/.svelte-kit/output/server/chunks/remote-1e3r2ap.js:14:26
    at ModuleJob.run (node:internal/modules/esm/module_job:271:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:547:26)
    at async analyse (file:///Users/hald/Documents/svelte-kit-remote-function-reproduction/node_modules/@sveltejs/kit/src/core/postbuild/analyse.js:173:34)
    at async MessagePort.<anonymous> (file:///Users/hald/Documents/svelte-kit-remote-function-reproduction/node_modules/@sveltejs/kit/src/utils/fork.js:23:16)

Node.js v22.12.0
```

### System Info

```Shell
System:
    OS: macOS 26.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 255.36 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.12.0 - /Users/hald/.nvm/versions/node/v22.12.0/bin/node
    npm: 11.4.2 - /Users/hald/.nvm/versions/node/v22.12.0/bin/npm
  Browsers:
    Chrome: 141.0.7390.67
    Firefox: 137.0.2
    Safari: 26.0
  npmPackages:
    @sveltejs/adapter-auto: ^6.1.0 => 6.1.1 
    @sveltejs/kit: ^2.43.2 => 2.46.4 
    @sveltejs/vite-plugin-svelte: ^6.2.0 => 6.2.1 
    svelte: ^5.39.5 => 5.39.11 
    vite: ^7.1.7 => 7.1.9
```

### Severity

blocking an upgrade

**Comment by dummdidumm** [comment]
This happens because of a circular dependency at the source: `query.ts` -> `Cell.svelte` -> `query.remote.ts` -> `query.ts`

Seems like our `manualChunks` approach cannot handle this case since it does not reorder the code such that the circular dependency is resolved.

**Comment by cofl** [comment]
I've encountered this in my project as well with what I'd think wouldn't be a problem:

```js
// _validation.ts
// only imported in the following two files
export const Schema = v.object(...)
```

```js
// form.remote.ts
// only imported in +page.svelte
import { Schema } from "./_validation"
export const myForm = form(Schema, ...)
```

```svelte
<!-- +page.svelte -->
<script lang="ts">
    import { myForm } from "./form.remote"

    // bug also occurs even without import {Schema} and preflight
    import { Schema } from "./_validation"
    const form = myForm.preflight(Schema)
</script>

<form {...form}>...</form>
```

As for why either situation would be considered circular, I'm not sure.

The linked PR does fix this scenario too.

Edit: As a workaround, duplicating the validation schema into the remote file also fixes the error.

**Comment by Torres1080** [comment]
> I've encountered this in my project as well with what I'd think wouldn't be a problem:
> 
> ```js
> // _validation.ts
> // only imported in the following two files
> export const Schema = v.object(...)
> ```
> 
> ```js
> // form.remote.ts
> // only imported in +page.svelte
> import { Schema } from "./_validation"
> export const myForm = form(Schema, ...)
> ```
> 
> ```svelte
> 
> <script lang="ts">
>     import { myForm } from "./form.remote"
> 
>     // bug also occurs even without import {Schema} and preflight
>     import { Schema } from "./_validation"
>     const form = myForm.preflight(Schema)
> </script>
> 
> <form {...form}>...</form>
> ```
> 
> As for why either situation would be considered circular, I'm not sure.
> 
> The linked PR does fix this scenario too.

I have a similar approach and after installing the latest commit of that PR my errors were fixed too.

**Comment by Blackwidow-sudo** [comment]
I still having issues when exporting the schema from a `<script module>` of a component.
When i export my schema from a `routes/+page.svelte` and use it in `routes/login.remote.ts`, the schema lands in `_page.js`, after the declaration of the remote form variable which then causes `ReferenceError [Error]: Cannot access 'schema' before initialization`
