### ISSUE TITLE
Build process stops at rendering chunks

### ISSUE THREAD

**Issue by nxy7** [sveltejs/kit#2991]
### Describe the bug

I'm not really sure if that's Vite or Sveltekit issue, so i've decided to post here.
My project works fine in dev mode, but i cannot build it. I've tried multiple adapters, node versions, sveltekit versions and few other things. Every time build halts at 'rendering chunks'.
<img width="267" alt="image" src="https://user-images.githubusercontent.com/32909532/144781343-925d58d8-b572-4f73-8922-1696943c989e.png">
I've created really minimal repo to reproduce the bug. Probably it's something that more experienced developer will solve in a blink of an eye (and here i am 4th hour trying to fix it xD).
Let me know if I could provide any more details. I couldn't find a way to get build logs (i dont even know if it's saved anywhere, since build process never really finishes, it just halts xD)

### Reproduction

https://github.com/nxy7/test

I've created repo reproducing the issue. Clone it, install dependencies and try to build it.

### System Info

```shell
win11
```

### Severity

blocking all usage of SvelteKit

**Comment by bluwy** [comment]
May be related to https://github.com/vitejs/vite/issues/5597 (thought the issue lacks a repro). It's likely a vite issue, though I haven't took a deeper look at it yet.

**Comment by nxy7** [comment]
I can confirm that
<img width="142" alt="image" src="https://user-images.githubusercontent.com/32909532/145211696-060c5f49-5a58-41ad-945d-53214834540c.png">
Solves the problem, although it's not the best long term solution. Thanks for linking the other issue @bluwy , I should be able to at least upload it now :-)

**Comment by IsaacHub** [comment]
vite looks like a horrible absurd bundler considering the number of issues and how childish and absurd those issues are. This vite nonsense is ruining the reputation of sveltekit. It's the only thing preventing the release of sveltekit. What a shame!

**Comment by nxy7** [comment]
> vite looks like a horrible absurd bundler considering the number of issues and how childish and absurd those issues are. This vite nonsense is ruining the reputation of sveltekit. It's the only thing preventing the release of sveltekit. What a shame!

To me vite seems great (even if there are still plenty of bugs). Give it more time to mature, both svelte and vite are amazing pieces of software :P

**Comment by benmccann** [comment]
If `vite.build.minify: false` fixes it, then it's almost certainly a Vite issue, so I will go ahead and close this issue since there's nothing that can be done about it in this repo. I recommend following up in the Vite repo. It could help them to have a reproducible test case

**Comment by vaghasiyaankur** [comment]
1 ) delete node_modules ( rm -rf node_modules ).
2 ) delete package-lock.json ( rm -rf package-lock.json ).
3 ) Removed unused packages in package.json file (Check all the packages to see if there is any where used. If not, remove it in package.json)
4 ) npm install and npm run build.

**Comment by vicentematus** [comment]
I resolved this by cloning again the repository. Im using Linux Mint 64 bits.

System Info

```
System:
    OS: Linux 5.15 Linux Mint 21.1 (Vera)
    CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
    Memory: 10.17 GB / 15.51 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
  Browsers:
    Chrome: 113.0.5668.0
    Firefox: 108.0.1
  npmPackages:
    @sveltejs/adapter-vercel: workspace:^ => 2.4.1 
    @sveltejs/amp: workspace:^ => 1.0.2 
    @sveltejs/kit: workspace:^ => 1.14.0 
    @sveltejs/site-kit: ^3.1.0 => 3.1.0 
    svelte: ^3.56.0 => 3.56.0 
    vite: ^4.2.0 => 4.2.0 
```

**Comment by uniboxx** [comment]
Hi, I encountered this error today and i solved with minify: false. 
My question is if there is a better solution that permit to minify the resulted files. Thanks.

**Comment by Septillion24** [comment]
For the sake of documentation, I encountered this issue today while building and `minify:false` did not fix it.
