### ISSUE TITLE
Config `paths.base` and `static` folder don't play well together

### ISSUE THREAD

**Issue by DblK** [sveltejs/kit#3267]
### Describe the bug

When adding a `path.base` all the path marked with `%svelte.assets%` are replaced with the path as expected.
This works great with `npm run build`.
However during dev mode, the `static` folder still represent `/` instead of the value of `path.base`.

### Reproduction

Add the following configuration:
```
kit: {
  ...,
  paths: {
    base: '/admin',
  },
}
```

And add `<link rel="stylesheet" href="%svelte.assets%/myCSS.css" />` in `app.html`.
In your `static` folder have the following structure:
```
| static
  |- myCss.css
```

The css in dev mode won't work unless you manually create the same folder
```
| static
  |- admin
    |- myCss.css
```

I wish to stick the file `myCss.css` at the root of `static` folder and let the magic happens to serve those file as if under `paths.base` (in my example `/admin/myCSS.css` stored in `static/myCSS.css`

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 128.55 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    npm: 7.24.0 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 89.0.2
    Safari: 14.0.3
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.9 
    @sveltejs/adapter-static: ^1.0.0-next.24 => 1.0.0-next.24 
    @sveltejs/kit: ^1.0.0-next.218 => 1.0.0-next.218 
    svelte: ^3.45.0 => 3.45.0
```

### Severity

serious, but I can work around it

### Additional Information

I add the path in my config for building but removing during dev. This is pretty annoying.

**Comment by DblK** [comment]
After search seems to be close to #3232

**Comment by ebeloded** [comment]
I just came here to report this exact issue, but you already did it 👍 

Issue #3232 description focuses on the static adapter, but the problem is the same for the `node-adapter`. Static assets location should respect `paths.base`.

**Comment by benmccann** [comment]
I think this should be fixed by https://github.com/sveltejs/kit/pull/3346

**Comment by lukaso** [comment]
Having just run into this issue now on 1.25.1, it is not fixed, unfortunately.
