### ISSUE TITLE
config.kit.alias sets wrong compilerOptions.paths

### ISSUE THREAD

**Issue by vekunz** [sveltejs/kit#5095]
### Describe the bug

In our `svelte.config.js` we have defined this options for `config.kit.alias`:
```js
alias: {
    $locales: "node_modules/svelte-intl-precompile/index.d.ts",
    "$locales/*": "src/locales/*"
}
```

Now SvelteKit creates these nodes in the `tsconfig.json` file:
```js
"$locales": [
    "node_modules/svelte-intl-precompile/index.d.ts"
],
"$locales/*": [
    "node_modules/svelte-intl-precompile/index.d.ts/*"
]
```

The problem is the entry for `$locales/*`. I think this entry is auto-generated, but SvelteKit should use the value that I provided in `svelte.config.js` instead of the auto-generated path.

### Reproduction

Just insert the config.kit.alias entries from above in your `svelte.config.js` and run `svelte-kit sync`.

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
    Memory: 10.86 GB / 31.79 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE      
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 101.0.4951.67
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.53)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-node: 1.0.0-next.73 => 1.0.0-next.73
    @sveltejs/kit: 1.0.0-next.345 => 1.0.0-next.345
    svelte: 3.48.0 => 3.48.0
```

### Severity

annoyance

**Comment by davecaruso** [comment]
I was the one who implemented `config.kit.alias`, and i did not think of this use case, or really any sort of behavior or error checking outside of simple aliases. When doing that, does kit/vite actually resolve the aliases at runtime properly (only ts has errors), or is it broken all around?

If it's just the tsconfig we need to change, I think all that's needed is:

1. if the alias target is only just a file (`index.d.ts`), do not set `${alias}/*` in `compilerOptions.paths` (doesn't apply to this, but probably something that should be done anyways)
2. if there are two aliases, one with a `/*` at the end, then the one without it shouldn't add it's `/*` at all.

I came up with that in my head just now, so it might be the exact solution needed to get typescript to resolve the aliases. But it's a general outline.

**Comment by david-plugge** [comment]
Cant you just reexport the module in an index.ts file?

**Comment by jarecsni** [comment]
I'm getting "Unexpected option config.kit.alias" (Svelte 3.48.0) - is this still supported?

**Comment by treboryx** [comment]
> I'm getting "Unexpected option config.kit.alias" (Svelte 3.48.0) - is this still supported?

Same here.

**Comment by vekunz** [comment]
> I'm getting "Unexpected option config.kit.alias" (Svelte 3.48.0) - is this still supported?

I don't think that this has anything to do with this issue. Please open an own Issue for your problem.

**Comment by vekunz** [comment]
By the way, we did not come up with the shortcuts $locale and $locale/* ourselves, but this is from the npm package svelte-intl-precompile.

**Comment by vekunz** [comment]
> ok fair enough. just out of curiosity, are you on the latest version of svelte?

Ii used the latest version of Svelte and SvelteKit to reproduce my problem. You can check the `System Info` section in the issue description for this.

**Comment by jarecsni** [comment]
> > ok fair enough. just out of curiosity, are you on the latest version of svelte?
> 
> I used the latest version of Svelte and SvelteKit to reproduce my problem. You can check the `System Info` section in the issue description for this.

I owe you an apology! I thought I was on the latest of everything whereas I was way behind on @sveltejs/kit...

**Comment by davecaruso** [comment]
I've been able to test what works and doesn't work from some potential aliases
```ts
alias: {
  // functional
  $a: 'src/alias',
  // functional
  $b: 'src/alias/direct-file.ts',
  // breaks tsc
  $c: 'src/alias/direct-file',
  // $d works, but $d/anything breaks tsc and vite
  $d: 'src/alias/direct-file.ts',
  '$d/*': 'src/alias/*', // the /* at the end of the value should be optional
  // breaks tsc and vite
  '$e/*': 'src/alias/*' // the /* at the end of the value should be optional
},
```

the main part of this is the fact that alias doesn't handle `/*` at all. here is a detailed overview of how alias resolving should work:

- alias name without `/*` matches itself and anything inside of the directory. this is how aliases work right now, and covers a majority of use cases.
- alias name ending with a `/*` matches anything inside of the directory given, but not the directory itself (see `$e` above; you should not be able to import `$e` but only something like `$e/stuff`), it overrides an alias of the same name without `/*`, so in the case of `$d` above, `$d` matches an exact file but `$d/stuff` matches a the other alias. (the issue that @vekunz is running into)
- alias values ending with a `/*` are seen as if the `/*` because aliases targeting a folder already do not need the `/*` and that is kind of assumed. we could also make this an config validation error.
- alias values targeting a file (in the case of $b and $c) should only target that file, which is not actually how our tsconfig is generated right now.
- `*` in any other part of the path, unless it actually is the name of a file or folder, should be a config validation error.

right now only the first bullet point is functional. i'm going to look into vite and tsc aliases to make sure this is possible, and attempt an implementation. if something about this should be changed, please comment.

**Comment by davecaruso** [comment]
im re-reading the initial message, and i'm confused why @vekunz is using config.kit.alias for `svelte-intl-precompile` when it seems to do it's own work with the aliasing. you just have to use their vite plugin.

that aside, i still think config.kit.alias was implemented a bit too simply and there should at least be some edge cases handled.

**Comment by vekunz** [comment]
> im re-reading the initial message, and i'm confused why @vekunz is using config.kit.alias for `svelte-intl-precompile` when it seems to do it's own work with the aliasing. you just have to use their vite plugin.

Yes, basically everything is working without additional configuration. The "problem" is the type resolution in the code editor. Without additional types configuration, the code editor (WebStorm in my case) shows every $locale import as an error.

**Comment by Mopholo** [comment]
I just upgraded svelte/kit and it now requires vite.config.js, which apparently also broke the all of our aliases

**Comment by flayks** [comment]
> I just upgraded svelte/kit and it now requires vite.config.js, which apparently also broke the all of our aliases
> 
> `alias: { $stores: './src/stores', $components: './src/components', $views: './src/views', $api: './src/endpointAPI' }`
> 
> These all worked fine until now. The error I get during build is
> 
> `[vite-plugin-svelte-kit] Cannot read properties of undefined (reading 'paths') error during build: TypeError: Cannot read properties of undefined (reading 'paths') at create_builder (file:///E:/Dev/my-app/node_modules/@sveltejs/kit/dist/chunks/index2.js:52:48)`
> 
> Seems related

Same issue as @Mopholo since yesterday and the new versions 🤔

**Comment by Valexr** [comment]
```
> Using @sveltejs/adapter-static
[vite-plugin-svelte-kit] Cannot read properties of undefined (reading 'paths')
error during build:
TypeError: Cannot read properties of undefined (reading 'paths')
```

**Comment by silvestrevivo** [comment]
I solved the error just removing the dynamic import with `await` inside the `onMount()` method. This has nothing to do apparently with TS or the configuration. @vekunz

**Comment by Mopholo** [comment]
I wish I could tell you how I solved it but I can't. 

I literally had to hand type what I was guessing was the offending file into a new file with the same name, and the problem stopped. 

A hex-editor showed them byte by byte compatible, but that dang error every time.

**Comment by Valexr** [comment]
> > Using @sveltejs/adapter-static
> [vite-plugin-svelte-kit] Cannot read properties of undefined (reading 'paths')
> error during build:
> TypeError: Cannot read properties of undefined (reading 'paths')

⚠️ resolved by right build flow config in mono repo 👌🏻 (not sveltekit bug)🤓

**Comment by vekunz** [comment]
> I solved the error just removing the dynamic import with `await` inside the `onMount()` method. This has nothing to do apparently with TS or the configuration. @vekunz

One the one hand, this does not solve the bug that config.kit.alias does not work correct. One the other hand it is never a good idea to create potential bugs intentionally.

**Comment by silvestrevivo** [comment]
@vekunz I thought the issue was related with `compilerOptions.paths` . Anyhow, I don't know what kind of issue this might introduce.

**Comment by vekunz** [comment]
> @vekunz I thought the issue was related with `compilerOptions.paths` . Anyhow, I don't know what kind of issue this might introduce.

Yes, it is related to `compilerOptions.paths`. But some `await` inside an `onMount()` is not related to this issue.
