### ISSUE TITLE
devalue cause crash on Netlify after update

### ISSUE THREAD

**Issue by wentallout** [sveltejs/kit#6462]
### Describe the bug

I updated some sveltekit-related npm packages then `build` successfully on local/dev but when deployed it just crashed on Netlify

```
Error - No "exports" main defined in /var/task/node_modules/devalue/package.json
```

### Reproduction

package.json
```
{
	"name": "portfolio",
	"version": "0.0.1",
	"scripts": {
		"dev": "vite dev",
		"build": "vite build",
		"preview": "vite preview",
		"check": "svelte-check --tsconfig ./jsconfig.json",
		"check:watch": "svelte-check --tsconfig ./jsconfig.json --watch",
		"test": "playwright test",
		"lint": "prettier --check . && eslint .",
		"format": "prettier --write .",
		"ngrok": "ngrok http 4173"
	},
	"devDependencies": {
		"@iconify-json/ph": "^1.1.2",
		"@playwright/test": "^1.25.0",
		"@supabase/supabase-js": "^1.35.6",
		"@sveltejs/adapter-auto": "next",
		"@sveltejs/adapter-netlify": "^1.0.0-next.75",
		"@sveltejs/kit": "next",
		"atropos": "^1.0.2",
		"eslint": "^8.16.0",
		"eslint-config-prettier": "^8.3.0",
		"eslint-plugin-svelte3": "^4.0.0",
		"normalize.css": "^8.0.1",
		"nprogress": "^0.2.0",
		"prettier": "^2.6.2",
		"prettier-plugin-svelte": "^2.7.0",
		"svelte": "^3.49.0",
		"svelte-check": "^2.8.0",
		"typescript": "^4.7.2",
		"unplugin-icons": "^0.14.8",
		"vite": "^3.1.0-beta.1",
		"vite-imagetools": "^4.0.5"
	},
	"type": "module"
}
```

### Logs

```shell
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /var/task/node_modules/devalue/package.json
    at new NodeError (node:internal/errors:372:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:472:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:693:7)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/var/task/.netlify/server/index.js:49:22)
```

### System Info

```shell
Binaries:
    Node: 17.9.0 - D:\nodejs\node.EXE
    npm: 8.5.3 - D:\nodejs\npm.CMD
  Browsers:
    Chrome: 104.0.5112.102
    Edge: Spartan (44.19041.1023.0), Chromium (104.0.1293.70)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.70
    @sveltejs/adapter-netlify: ^1.0.0-next.75 => 1.0.0-next.75
    @sveltejs/kit: next => 1.0.0-next.456
    svelte: ^3.49.0 => 3.49.0
    vite: ^3.1.0-beta.1 => 3.1.0-beta.1
```

### Severity

blocking all usage of SvelteKit

### Additional Information

I did look at some reports on discord and changed my vite version to "vite": "^3.1.0-beta.1",

**Comment by MajorBreakfast** [comment]
<img width="891" alt="Screen Shot 2022-08-31 at 20 21 00" src="https://user-images.githubusercontent.com/340142/187752228-6be9a4da-3059-4b4d-b5aa-65873923c903.png">

Just to visualize the error :)

**Comment by rowantrollope** [comment]
Having the same issue on vercel

**Comment by MajorBreakfast** [comment]
Looking at the `package.json` of `devalue`, it does not have a `main` field. My (unconfirmed) guess is that this is the issue

https://github.com/Rich-Harris/devalue/blob/master/package.json

**Comment by rowantrollope** [comment]
The error I'm seeing on verbal is: 

"SyntaxError: Named export 'devalue' not found. The requested module 'devalue' is a CommonJS module, which may not support all module.exports as named exports."

Screenshot attached. 

<img width="1197" alt="Screenshot 2022-09-01 at 1 49 28 PM" src="https://user-images.githubusercontent.com/11445749/188010595-0bcdb4bc-4b1f-403a-82f2-ff639d768b59.png">

**Comment by geoffrich** [comment]
This issue is happening because the new version of `devalue` is ESM-only, and Netlify is trying to `require` it. The maintainers are working on a more permanent solution, but in the meantime you can temporarily work around the issue one of the following ways:

1. Configure Netlify to bundle your functions [with esbuild](https://docs.netlify.com/configure-builds/file-based-configuration/#functions). In a `netlify.toml` at the root of the project:

```toml
[build]
  command = "npm run build"
  publish = "build"

[functions]
  node_bundler = "esbuild" # temporary workaround for https://github.com/sveltejs/kit/issues/6462
```


2. Deploy using Netlify edge functions. In your `svelte.config.js`:

```diff
import netlify from '@sveltejs/adapter-netlify';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
+		adapter: netlify({ edge: true })
-		adapter: netlify()
	}
};

export default config;
```

**Comment by geoffrich** [comment]
For those reporting a similar issue on Vercel -- can you provide a repro? I was able to reproduce this issue with a fresh demo project on Netlify, but not on Vercel.

**Comment by demetrius-mp** [comment]
> For those reporting a similar issue on Vercel -- can you provide a repro? I was able to reproduce this issue with a fresh demo project on Netlify, but not on Vercel.

the issue i was having on vercel is not related to devalue, but to [this](https://vercel.com/guides/why-does-my-serverless-function-work-locally-but-not-when-deployed)

**Comment by xpat** [comment]
Also crashes for me on adapter-node.

```
import devalue from "devalue";
       ^^^^^^^
SyntaxError: The requested module 'devalue' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:127:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:191:5)
    at async Promise.all (index 0)
```
[In another issue related to this](https://github.com/Rich-Harris/devalue/issues/24), it was suggested that the problem could be fixed by setting "true" at "esModuleInterop": true,
but my tsconfig.json already had it set to true.

```
cat tsconfig.json 
{
        "extends": "./.svelte-kit/tsconfig.json",
        "compilerOptions": {
                "moduleResolution": "node",
                "module": "es2020",
                "lib": ["es2020", "DOM"],
                "target": "es2020",
                /**
                svelte-preprocess cannot figure out whether you have a value or a type, so tell TypeScript
                to enforce using \`import type\` instead of \`import\` for Types.
                */
                "importsNotUsedAsValues": "error",
                "isolatedModules": true,
                "resolveJsonModule": true,
                /**
                To have warnings/errors of the Svelte compiler at the correct position,
                enable source maps by default.
                */
                "sourceMap": true,
                "esModuleInterop": true,
                "skipLibCheck": true,
                "forceConsistentCasingInFileNames": true,
                "baseUrl": ".",
                "allowJs": true,
                "checkJs": true,
                "paths": {
                        "$lib": ["src/lib"],
                        "$lib/*": ["src/lib/*"],
                        "$img": ["src/images"]
                }
        },
        "include": ["src/**/*.d.ts", "src/**/*.js", "src/**/*.ts", "src/**/*.svelte"]
}
```

**Comment by Rich-Harris** [comment]
The issue described in the OP is happening because Netlify doesn't support ESM (https://github.com/netlify/zip-it-and-ship-it/issues/750), and recent versions of SvelteKit depend on `devalue@3` which is an ESM package.

Ultimately, this will continue to affect _any_ app deployed to Netlify that has an ESM dependency — we've just been lucky not to stumble onto one until now. As more of the ecosystem goes ESM-only, this will happen more frequently.

The reason this doesn't happen if you specify `node_bundler=esbuild` is that unlike the default `zisi` (zip-it-and-ship-it), `esbuild` bundles everything to a single file rather than just zipping up stuff in `node_modules`. But that's too blunt a remedy — `esbuild` can't bundle everything (i.e. native dependencies).

I think the solution is to adopt the same strategy `adapter-node` has — use `esbuild` within the adapter to bundle everything in `devDependencies`, but leave prod dependencies unbundled. If you're using `zisi` then native dependencies will continue to work, and if you're using `esbuild` then it will just get bundled a second time, harmlessly.

@xpat looks like you have some out-of-date dependencies somewhere — if something is doing this...

```js
import devalue from 'devalue'
```

...it means it's expecting `devalue@2`, not `devalue@3` (which uses a named export).

@rowantrollope seems like you have the opposite problem — that code expects `devalue@3`, but you might have `devalue@2` installed somehow?

**Comment by rowantrollope** [comment]
Thanks Rich,

Confirmed! Somehow I had an old devalue installed.  I didn't see it in my package.json so I don't know where it came from.  Are there packages installed that don't show up in package.json?

At any rate, I just did a pnpm install ***@***.*** and that fixed the problem.

Out of curiosity (for others who run into this), how do I find the dependency that had installed the older devalue? If @sveltejs/kit requires ***@***.*** why wouldn't pnpm have installed it?

Thank you!
Rowan

Sent via Superhuman ( ***@***.*** )

**Comment by StephenGunn** [comment]
@geoffrich Thanks for that fix.. I tried it and it kind of worked. Most of the dynamic routes that were broken started working.. But other things started breaking. I had some weird formatting and a few dynamic routes just wouldn't load on the live server. They would 404 and the data requests wouldn't even hit my backend. 

They all built and ran fine locally with pnpm build / pnpm preview. 

Just wanted to give a heads up. I obviously have tempered expectations using software that's in beta and am fine waiting for a fix.

Let me know if there is anything I can do for you to help troubleshoot.

Thanks for all your hard work :)

**Comment by MajorBreakfast** [comment]
I think I'm back in business on Netlify.

- @Rich-Harris released `devalue@3.1.3` which adds the `main` field in `package.json` and made sure that my `package-lock.json` specifies the `3.1.3` version ([link to commit in devalue repo](https://github.com/Rich-Harris/devalue/commit/4411fbba673d77b70ece777f1f481fa7c937ae22))
- I added `'devalue'` to `ssr.noExternal` array in the Vite config

After doing both steps it works. My `ssr.noExternal` array already contained other ESM packages before that.

**Comment by pilcrowOnPaper** [comment]
I was able to get something deployed by adding `devalue` to `ssr.noExternal`, though I'm not sure if everything works

**Comment by flaced** [comment]
> The error I'm seeing on verbal is:
> 
> "SyntaxError: Named export 'devalue' not found. The requested module 'devalue' is a CommonJS module, which may not support all module.exports as named exports."
> 
> Screenshot attached.
> 
> <img alt="Screenshot 2022-09-01 at 1 49 28 PM" width="1197" src="https://user-images.githubusercontent.com/11445749/188010595-0bcdb4bc-4b1f-403a-82f2-ff639d768b59.png">

for everyone having the same issue on vercel:

i managed to fix it in my vercel project by simply running:
`pnpm i devalue`

**Comment by ascorbic** [comment]
I'm sorry for the pain this is causing people. I want to confirm that Netlify is prioritising a fix for this, to allow ESM entrypoints. In the meantime, would an approach similar to [the one used by Nuxt](https://github.com/unjs/nitro/blob/main/src/presets/netlify.ts#L36-L44) do the job? They have a CJS entrypoint that dynamically imports the ESM bundle.

**Comment by sonyarianto** [comment]
Hi I am doing like this, refering to this https://github.com/Rich-Harris/devalue/issues/36

- Remove `package-lock.json` (because still contains devalue 3.1.2)
- Remove `pnpm.yaml` (because still contains devalue 3.1.2)
- Run `pnpm install`
- Edit vite.config.js to this

```
const config = {
	plugins: [sveltekit()],
	ssr: {
		noExternal: ['devalue']
	}
};
```

- Build on Vercel
- Build success!

**Comment by secondl1ght** [comment]
Will this be fixed in the next SvelteKit release?

**Comment by suryamsj** [comment]
I'm also having the same problem. But when I change vite.config.js to like this

```js
const config = {
	plugins: [sveltekit()],
	ssr: {
		noExternal: ['devalue']
	}
};
```

everything is working normally and everything seems to be working

**Comment by geoffrich** [comment]
This appears to have been fixed with #6666 -- my Netlify sites now work as expected on the latest adapter version. @wentallout (and others in this thread) can you remove any workarounds in `netlify.toml` or `svelte.config.js` and update to the latest Netlify adapter to see if that fixes your issue?

**Comment by secondl1ght** [comment]
Awesome - just updated packages to latest and removed the workaround from `netlify.toml` and it deploys normally again. Thanks!

**Comment by sonyarianto** [comment]
ok, I removed the work around on ` vite.config.js` and build on Vercel and it works :) Thank you. @geoffrich

**Comment by wentallout** [comment]
I updated all the packages to newest and everything works normally.

**Comment by geoffrich** [comment]
Closing since the issue appears to have been fixed.

**Comment by tedsteen** [comment]
Hmm, what am I missing?

My package.json contains
```json
"@sveltejs/adapter-netlify": "next",
"@sveltejs/kit": "next",
```

My netlify.toml looks like this
```yaml
[build]
  command = "npm run build"
  publish = "build"

[[plugins]]
package = 'netlify-plugin-contextual-env'
```

and my vite.config.js
```js
import { sveltekit } from '@sveltejs/kit/vite';
import { imagetools } from 'vite-imagetools';

/** @type {import('vite').UserConfig} */
const config = {
	plugins: [sveltekit(), imagetools()],
	resolve: {
		preserveSymlinks: true
	}
};

export default config;
```

I did `npm update` and I still get `Error - No "exports" main defined in /var/task/node_modules/devalue/package.json` when I deploy to netlify.

**Comment by geoffrich** [comment]
@tedsteen can you paste the output of `npx envinfo --npmPackages "{svelte,@sveltejs/*,vite}"`?

I can't repro on the SvelteKit demo app - can you provide a minimal repo reproducing the issue?

**Comment by MajorBreakfast** [comment]
BTW just tested out of curiosity what happens if `devalue@3.1.2` (not `3.1.3`) is installed: I'm seeing that the older version works now as well. With the latest Netlify adapter there's no problem anymore.

@tedsteen Just `"next"` in the `package.json` isn't forceful enough. If a `node_modules/` folder or a `package-lock.json` still exist, it will pick the same versions as last time. I can recommend using the tool [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) for updating the `package.json`. Or alternatively delete the `node_modules/` folder and `package-lock.json`, run `npm i` and take a look at the git diff of the `package-lock.json` to see whether it updated all the desired packages.

**Comment by tedsteen** [comment]
> npx envinfo --npmPackages "{svelte,@sveltejs/*,vite}"

❯ npx envinfo --npmPackages "{svelte,@sveltejs/*,vite}"

  npmPackages:
    @sveltejs/adapter-netlify: next => 1.0.0-next.77
    @sveltejs/kit: next => 1.0.0-next.481
    svelte: ^3.49.0 => 3.50.1

**Comment by tedsteen** [comment]
> Just `"next"` in the `package.json` isn't forceful enough. If a `node_modules/` folder or a `package-lock.json` still exist, it will pick the same versions as last time. I can recommend using the tool [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) for updating the `package.json`. Or alternatively delete the `node_modules/` folder and `package-lock.json`, run `npm i` and take a look at the git diff of the `package-lock.json` to see whether it updated all the desired packages.

Didn't make a difference (it seems like npm update does update next versions?)

**Comment by tedsteen** [comment]
I'm not sure what happened, but now it works and I can't seem to revert to a broken version.

**Comment by wvhulle** [comment]
Putting "devalue": "^3.1.3" in my dependencies section of package.json fixed it.

**Comment by rowantrollope** [comment]
Will try. FWIW I lBacked off the latest sveltekit build to sveltekit 443 , still had problem. Then explicitly removed devalue from package json: problem fixed.

Sent via Superhuman iOS ( ***@***.*** )

**Comment by janosh** [comment]
Anyone else still/again seeing this in netlify builds with `adapter-static` during pre-rendering?

> 9:40:24 PM: .svelte-kit/output/server/chunks/hooks.js                                      0.00 KiB
**9:40:24 PM: TypeError: devalue.uneval is not a function**
9:40:24 PM:     at render_response (file:///opt/build/repo/.svelte-kit/output/server/index.js:1111:31)
9:40:24 PM:     at async render_page (file:///opt/build/repo/.svelte-kit/output/server/index.js:1501:12)
9:40:24 PM:     at async resolve (file:///opt/build/repo/.svelte-kit/output/server/index.js:1994:22)
9:40:24 PM:     at async respond (file:///opt/build/repo/.svelte-kit/output/server/index.js:2032:22)
9:40:24 PM:     at async visit (file:///opt/build/repo/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.517_svelte@3.52.0+vite@3.1.8/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:226:20)

https://app.netlify.com/sites/svelte-bricks/deploys/634f7f8bafaf8e0009a09e15#L153

**Comment by brittneypostma** [comment]
@janosh I am currently using `adapter-static` on Netlify and not seeing this error. If you still need help, post your `netlify.toml` file if you have one, your `svelte.config.js` , and output of `npx envinfo --npmPackages "{svelte,@sveltejs/*,vite}"`.

**Comment by janosh** [comment]
@brittneypostma I just `pnpm add -D devalue` to solve the problem. But would be interesting to find out why `devalue` wasn't installed automatically.
