### ISSUE TITLE
Can't set cookies/headers inside `handle` hook after call to `resolve`

### ISSUE THREAD

**Issue by iceghost** [sveltejs/kit#6735]
### Describe the bug

`handle` hook doesn't add cookies as expected

### Reproduction

https://stackblitz.com/edit/node-shcasv

step 1: create a skeleton project
step 2: add `hooks.server.js`:

```js
/** @type {import("@sveltejs/kit").Handle} */
export async function handle({ event, resolve }) {
    console.log('hook ran');
    event.cookies.set('some', 'value', { secure: false, httpOnly: false });
    return await resolve(event);
}
```

step 3: open the site
step 4: try deleting the cookie (if present) on the browser and refresh. no new cookie is added

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 2.05 GB / 3.73 GB
    Container: Yes
    Shell: 3.5.0 - /usr/bin/fish
  Binaries:
    Node: 18.7.0 - ~/.local/share/nvm/v18.7.0/bin/node
    Yarn: 1.22.10 - /mnt/c/Users/_/AppData/Roaming/npm/yarn
    npm: 8.15.0 - ~/.local/share/nvm/v18.7.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.72 
    @sveltejs/kit: next => 1.0.0-next.480 
    svelte: ^3.44.0 => 3.50.1 
    vite: ^3.1.0 => 3.1.0
```

### Severity

blocking all usage of SvelteKit

**Comment by cdcarson** [comment]
I think this is a duplicate of #6650. 

@iceghost Cookie issues ar being worked on in #6648

**Comment by benmccann** [comment]
Hopefully this is fixed in the latest release by https://github.com/sveltejs/kit/pull/6811

**Comment by iceghost** [comment]
@benmccann I'm sorry, but it didn't fix it. Can this be reopened?

**Comment by david-plugge** [comment]
`setHeaders` doesn´t work too

**Comment by dummdidumm** [comment]
I can't reproduce this, headers and cookies are applied for me. Could this be a cache problem; that you get a cached response (you can turn of caching in the network tab of the browser devtools)

**Comment by iceghost** [comment]
@dummdidumm Ah yes, indeed. Turning off caching works. So I have to add:

```js
// hooks.server.js#handle
event.setHeaders({ 'Cache-Control': 'no-cache' });
```

I'm not sure of the implication of this, but I guess we can close the issue now

**Comment by david-plugge** [comment]
https://github.com/david-plugge/issue-sveltekit-cookies-handle
It doesnt work for me, i disabled cache in the network tab.

**Comment by iceghost** [comment]
> https://github.com/david-plugge/issue-sveltekit-cookies-handle It doesnt work for me, i disabled cache in the network tab.

In `handleCallback`, setting cookies on `event` has no effect since you are returning `json(...)`, which has no knowledge about `event`. If you want to return the cookies, maybe supply a manual `Set-Cookie` header will work.

```js
import { serialize } from 'cookie';

async function handleCallback({ request }: RequestEvent) {
	const { type, username } = await request.json();

	const headers = new Headers();
	if (type === 'signin') {
		console.log('callback signin');
		headers.append(
			'Set-Cookie',
			serialize('username', username, {
				path: '/',
				maxAge: 3600
			})
		);
	} else if (type === 'signout') {
		console.log('callback signout');
		headers.append(
			'Set-Cookie',
			serialize('username', '', {
				path: '/'
			})
		);
	}

	return json({ success: true }, { headers });
}
```

I think I will close the issue first...

**Comment by david-plugge** [comment]
@iceghost but it could be implemented as i said in a comment above. And if you use cookies in a request handler eg. `+server.ts` you can use cookies **and** return with json

**Comment by dummdidumm** [comment]
It certainly needs to be called upon resolve because people could rely on the headers already being present on the response object when resolve returns. I'm not sure if it's "works as designed" and needs to be documented as a caveat or if we should apply any additional cookies/headers that were set after resolve. Reopening and changing the title accordingly until we decide that.

**Comment by david-plugge** [comment]
Thanks!

Currently setting headers and cookies without calling resolve doesnt work aswell.
This could be resolved if the headers and cookies are set upon resolve **and** after the handle hook.

**Comment by benquan** [comment]
Facing same issue here. I can get the cookie but cannot set or delete it from hooks.server.ts

**Comment by homerjam** [comment]
> @dummdidumm Ah yes, indeed. Turning off caching works. So I have to add:
> 
> ```js
> // hooks.server.js#handle
> event.setHeaders({ 'Cache-Control': 'no-store' });
> ```
> 
> I'm not sure if this is the correct way, but I guess we can close the issue now

This was crucial for me to have cookies sent with the response. Without it only the first response from sveltekit would include the set-cookie header.

**Comment by benquan** [comment]
I have this **hooks.server.ts** file:

```
import type { Handle } from '@sveltejs/kit';

export const handle: Handle = async ({ event, resolve }) => {
	const counter = event.cookies.get('counter');
	const newCounter = parseInt(counter ?? '0') + 1;
	event.cookies.set('counter', newCounter.toString(), { path: '/' });

	console.log(`Hook Fired: ${counter} - ${newCounter}`);
	return await resolve(event);
};
```

In theory it should increase the counter on every page load. But...

1) If I change page, hooks is fired and counter increased. (OK)
2) If I go to '/' home page, hooks will not fire (is this normal?)
3) If I do a refresh on any page, hooks fires but counter is not increased. (normal?)





```

**Comment by david-plugge** [comment]
Maybe a caching issue?

**Comment by benquan** [comment]
Number 2 is because it's a client side call so no server is involved. OK it's normal. But on 3. The server is called and processed but the cookie is not updated.

**Comment by homerjam** [comment]
> > @dummdidumm Ah yes, indeed. Turning off caching works. So I have to add:
> > ```js
> > // hooks.server.js#handle
> > event.setHeaders({ 'Cache-Control': 'no-store' });
> > ```
> >   
> > I'm not sure if this is the correct way, but I guess we can close the issue now
> 
> This was crucial for me to have cookies sent with the response. Without it only the first response from sveltekit would include the set-cookie header.

@benquan did you try this?

**Comment by benquan** [comment]
That worked! I thought the recent merge had made that unnecessary!

**Comment by benquan** [comment]
One more doubt.

I understand that cookies will only work if you do
`return await resolve(event);`

what if I want to redirect?

I tried 
```
		event.url.pathname = '/auth/login';
		event.url.search = '';
```

but will not work

also tried doing a new Response(...) but the cookie change is lost.

Any other alternative?

**Comment by homerjam** [comment]
@benquan I guess you want something like

```js
event.setHeaders({ 'Location': '/auth/login' });
```

**Comment by benquan** [comment]
yes but that won't work, already tried it.

**Comment by david-plugge** [comment]
@benquan take a look at the [docs](https://kit.svelte.dev/docs), you can search for `redirect`.

You can always redirect manually using the location headers as suggested by @homerjam.
Since `setHeaders` only applies to the response returned by `resolve(event)` you´d have to set the headers like this if you dont call resolve:

```ts
return new Response(..., {
	headers: { 'Location': '/auth/login' }
})
```

**Comment by iceghost** [comment]
> yes but that won't work, already tried it.

Maybe you forgot to set the status to 3xx
