### ISSUE TITLE
return fail() fails with Error: Data returned from action inside / is not serializable: Cannot stringify arbitrary non-POJOs

### ISSUE THREAD

**Issue by blerrgh** [sveltejs/kit#8523]
### Describe the bug

As of sveltekit 1.0.13, returning a fail() object from an Action fails with the following error when using `npm run dev`

```
Error: Data returned from action inside / is not serializable: Cannot stringify arbitrary non-POJOs
```

Everything worked fine in 1.0.12.  Also works as expected using `npm run build` / `npm run preview`

### Reproduction

`+page.server.js`
```javascript
import { fail } from '@sveltejs/kit';

/** @type {import('./$types').Actions} */
export const actions = {
	test: async () => {
		return fail(500);
	},
};
```

`+page.svelte`
```html
<form method="POST" action="?/test">
	<button>Submit</button>
</form>
```

### Logs

```Shell
Error: Data returned from action inside / is not serializable: Cannot stringify arbitrary non-POJOs
    at try_deserialize (/node_modules/@sveltejs/kit/src/runtime/server/page/actions.js:262:10)
    at stringify_action_response (/node_modules/@sveltejs/kit/src/runtime/server/page/actions.js:244:9)
    at Module.handle_action_json_request (/node_modules/@sveltejs/kit/src/runtime/server/page/actions.js:67:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:358:17)
    at async Module.respond (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:229:20)
    at async file:///C:/Users/geoff/slingshot/slingshot-webui/frontend/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:468:22
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 33.87 GB / 63.95 GB
  Binaries:
    Node: 19.3.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.3.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 109.0.5414.74
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0
    @sveltejs/adapter-node: ^1.0.0 => 1.1.1
    @sveltejs/kit: ^1.0.12 => 1.1.0
    svelte: ^3.46.0 => 3.55.1
    vite: ^4.0.0 => 4.0.4
```

### Severity

blocking an upgrade

**Comment by dummdidumm** [comment]
`devalue` is the package responsible for serializing this, it was recently updated. Can you try pinning its version to two and one version earlier and see if that makes a difference?

**Comment by blerrgh** [comment]
> Can you try pinning its version to two and one version earlier and see if that makes a difference?

Overriding devalue back to 4.2.0 doesn't make a difference, I'm still getting the error.

**Comment by bobthered** [comment]
@blerrgh I'm not sure if you're still looking into this, but I had the same issue.  I found that updating all packages `npm update` updated `devalue` to `4.2.2`.  This should have fixed it, but I still kept getting the error.  Once I deleted the `.svelte-kit` folder, and restarted the server, it fixed it

**Comment by NormandoHall** [comment]
Same here with `devalue@4.2.2`

**Comment by benlau6** [comment]
Same here with `throw redirect(303, '/login')`, but it got fixed by https://github.com/sveltejs/kit/issues/8523#issuecomment-1383160595, and somehow I needa do it multiple times

**Comment by blerrgh** [comment]
> Once I deleted the `.svelte-kit` folder, and restarted the server, it fixed it

Thanks @bobthered, removing the `.svelte-kit` folder solved this issue for me as well.

**Comment by NormandoHall** [comment]
Only for reference, this cause me thrown error to any redirect. #8539 

@blerrgh may be you want to reopen this because it still an issue.

**Comment by Yiak** [comment]
Same problem.
In action, `throw redirect(303, path)` got fixed by [comment](https://github.com/sveltejs/kit/issues/8523#issuecomment-1383160595), but `return redirect(303, path)` still fails with Error: `Data returned from action inside / is not serializable: Cannot stringify arbitrary non-POJOs`. In my case I need to use return instead of throw, otherwise it would be messed up with the try-catch logic.

**Comment by dummdidumm** [comment]
@Yiak you cannot `return redirect(..)`, that doesn't do a redirect, it will try to serialize `redirect` as a value, which is why you get that error.

**Comment by Rich-Harris** [comment]
I can't reproduce this. Does anyone have a repo showing the issue?

**Comment by Yiak** [comment]
@Rich-Harris Sorry I don't have the repo to show the issue because the issue will disappear after a rerun of `pnpm dev`. But this happened again today when I renamed the route that was pointed by a form from an independent component while the dev server was running. I think this is not a big deal since it will be fixed just by a rerun...

**Comment by dummdidumm** [comment]
I tried to reproduce this but can't. If anyone has a reproducible, please post it. The reproducible doesn't have to minimal, if it's reproducible with any of your open source projects, just post the link to it. What I'm more interested in is the _steps_ which lead to this error appearing. So if this occurs the next time please write down what happened. Example:
1. `npm run dev`
2. did X (this can be anything! "updated Svelte while the dev server was running", "changed something in the `svelte.config.js` file", everything could be important)
3. doesn't work anymore

**Comment by blerrgh** [comment]
https://github.com/blerrgh/sveltekit-devalue-not-serializable-repro  try this.  Steps to reproduce are in the readme.

I spent some time this morning trying to get a minimal reproduction.  The key seems to have something to do with vite optimizing dependencies.  I couldn't get it to work unless I added a random dependency to package.json (svelte-headless-table in this case, but I don't think it matters specifically what the package is.)

Fail() and throw() work fine until I see 

```
11:08:56 AM [vite] ✨ new dependencies optimized: svelte-headless-table
11:08:56 AM [vite] ✨ optimized dependencies changed. reloading
````

And then they start erroring.  Re-running `npm run dev` usually fixes the issue _until_ it optimizes dependencies again.

Let me know if you're able to reproduce it.

(Also, I am on windows 10 -- haven't tested this under linux.)

**Comment by 524c** [comment]
The same here. I spent some time trying to understand the problem and I still couldn't. The error disappeared after deleting the .svelte-kit folder.

I'll try to retrace my steps by installing two older versions of @sveltejs/kit and then go with one update at a time and see if I can reproduce again.

**Comment by 524c** [comment]
> https://github.com/blerrgh/sveltekit-devalue-not-serializable-repro try this. Steps to reproduce are in the readme.
> 
> I spent some time this morning trying to get a minimal reproduction. The key seems to have something to do with vite optimizing dependencies. I couldn't get it to work unless I added a random dependency to package.json (svelte-headless-table in this case, but I don't think it matters specifically what the package is.)
> 
> Fail() and throw() work fine until I see
> 
> ```
> 11:08:56 AM [vite] ✨ new dependencies optimized: svelte-headless-table
> 11:08:56 AM [vite] ✨ optimized dependencies changed. reloading
> ```
> 
> And then they start erroring. Re-running `npm run dev` usually fixes the issue _until_ it optimizes dependencies again.
> 
> Let me know if you're able to reproduce it.
> 
> (Also, I am on windows 10 -- haven't tested this under linux.)

Same here.

I thought it was something about a mix up between the artifacts in .svelte-kit and the package version after an upgrade, but it happened here right after this message:
```
12:57:39 PM [vite] ✨ new dependencies optimized: yup
12:57:39 PM [vite] ✨ optimized dependencies changed. reloading
```

**Comment by ciscoheat** [comment]
I've had the same problem infrequently, but it usually went away after restarting VS Code. But more frequently I have had a similar problem with `redirect` in `+page.server.ts` files.

After throwing a redirect, it won't get caught but instead goes to the `handleError` function in `hooks.server.ts`, instead of redirecting. Restarting the dev server makes it go away, but it appears again frequently enough now to be annoying.

Stack trace:
```
at Object.handleError (/src/hooks.server.ts:55:13)
at Module.handle_error_and_jsonify (/node_modules/.pnpm/@sveltejs+kit@1.2.1_262zhp54rffy2bklrl2ynkhpha/node_modules/@sveltejs/kit/src/runtime/server/utils.js:149:25)
at Module.handle_action_json_request (/node_modules/.pnpm/@sveltejs+kit@1.2.1_262zhp54rffy2bklrl2ynkhpha/node_modules/@sveltejs/kit/src/runtime/server/page/actions.js:93:40)
at async resolve (/node_modules/.pnpm/@sveltejs+kit@1.2.1_262zhp54rffy2bklrl2ynkhpha/node_modules/@sveltejs/kit/src/runtime/server/respond.js:365:17)
at async eval (/node_modules/.pnpm/@lucia-auth+sveltekit@0.5.2_fec62evc6llxeegip47f74apjq/node_modules/@lucia-auth/sveltekit/server/hooks.js:87:16)
at async Module.respond (/node_modules/.pnpm/@sveltejs+kit@1.2.1_262zhp54rffy2bklrl2ynkhpha/node_modules/@sveltejs/kit/src/runtime/server/respond.js:236:20)
at async file:///.../node_modules/.pnpm/@sveltejs+kit@1.2.1_262zhp54rffy2bklrl2ynkhpha/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:467:22
```

There could be some correlation with the dependency optimization and SSR compilation that `vite` and `vite-plugin-svelte` are doing, but I'm not sure.

**Comment by jhwz** [comment]
> I've had the same problem infrequently, but it usually went away after restarting VS Code. But more frequently I have had a similar problem with `redirect` in `+page.server.ts` files.
> 
> After throwing a redirect, it won't get caught but instead goes to the `handleError` function in `hooks.server.ts`, instead of redirecting. Restarting the dev server makes it go away, but it appears again frequently enough now to be annoying.
> 
> Stack trace:
> 
> ```
> at Object.handleError (/src/hooks.server.ts:55:13)
> at Module.handle_error_and_jsonify (/node_modules/.pnpm/@sveltejs+kit@1.2.1_262zhp54rffy2bklrl2ynkhpha/node_modules/@sveltejs/kit/src/runtime/server/utils.js:149:25)
> at Module.handle_action_json_request (/node_modules/.pnpm/@sveltejs+kit@1.2.1_262zhp54rffy2bklrl2ynkhpha/node_modules/@sveltejs/kit/src/runtime/server/page/actions.js:93:40)
> at async resolve (/node_modules/.pnpm/@sveltejs+kit@1.2.1_262zhp54rffy2bklrl2ynkhpha/node_modules/@sveltejs/kit/src/runtime/server/respond.js:365:17)
> at async eval (/node_modules/.pnpm/@lucia-auth+sveltekit@0.5.2_fec62evc6llxeegip47f74apjq/node_modules/@lucia-auth/sveltekit/server/hooks.js:87:16)
> at async Module.respond (/node_modules/.pnpm/@sveltejs+kit@1.2.1_262zhp54rffy2bklrl2ynkhpha/node_modules/@sveltejs/kit/src/runtime/server/respond.js:236:20)
> at async file:///.../node_modules/.pnpm/@sveltejs+kit@1.2.1_262zhp54rffy2bklrl2ynkhpha/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:467:22
> ```
> 
> There could be some correlation with the dependency optimization and SSR compilation that `vite` and `vite-plugin-svelte` are doing, but I'm not sure.

I'm also seeing this same behaviour when the issue occurs. I can't reproduce the error consistently, but when it does pop up it comes from a `throw redirect()` statement which somehow makes it into the `handleError` function.

In my logs I see (from `console.error('SERVER ERROR:\n', error);`)
```
SERVER ERROR:
 Redirect { status: 303, location: '/' }
```

**Comment by danisal** [comment]
Facing the same problem here ✋; if there is a need for a repository to reproduce it, I can help with that.

**Comment by svex99** [comment]
I wasted so much time on this error, I was just refactoring some code when it came up. Restarting the development server fixed it, at least for the moment.

**Comment by yb-leakmited** [comment]
Am I the only one having a problem with this issue even with the latest sveltekit & vite ?

**Comment by pheuter** [comment]
> Am I the only one having a problem with this issue even with the latest sveltekit & vite ?

Check if you are returning any values in `return fail()` that cannot be serialized. A common one is `File` if your form handles multipart file uploads.
