### ISSUE TITLE
Flash of unstyled content in dev mode

### ISSUE THREAD

**Issue by mishrasatyam** [sveltejs/kit#915]
**Describe the bug**
Css feels wierd while reload in dev environment. Works fine with build output

**To Reproduce**
Using below dependencies:
"@sveltejs/adapter-node": "next",
"@sveltejs/kit": "next",
"svelte": "^3.29.0",
"vite": "^2.1.0"

**Video**

https://user-images.githubusercontent.com/31180325/113860495-bb328800-97c3-11eb-9495-7718935dfb1d.mp4

**Comment by benmccann** [comment]
This sounds like it could be coming from https://github.com/vitejs/vite/issues/2282

**Comment by saturnonearth** [comment]
Has anyone noticed this issue on prod? I am having some weird CSS flashes on refresh, even for a cached browser. Seems to happy mainly, if not only, on Chrome for Windows. Not sure if this is a Svelte issue or Chrome

**Comment by crinklesio** [comment]
> Has anyone noticed this issue on prod? I am having some weird CSS flashes on refresh, even for a cached browser. Seems to happy mainly, if not only, on Chrome for Windows. Not sure if this is a Svelte issue or Chrome

I definitely have this issue on Brave (chromium) on MacOS as well. Mitigated it by setting the following style on the `app.html` .

```
<style>
   html { visibility: hidden; }
<style>
```

And in the main CSS file I am using, set the visibility to `visible !important`. Similarly, you can use a `:global(html) { ... }` on your `__layout.svelte` for instance.

**Comment by saturnonearth** [comment]
> > Has anyone noticed this issue on prod? I am having some weird CSS flashes on refresh, even for a cached browser. Seems to happy mainly, if not only, on Chrome for Windows. Not sure if this is a Svelte issue or Chrome
> 
> I definitely have this issue on Brave (chromium) on MacOS as well. Mitigated it by setting the following style on the `app.html` .
> 
> ```
> <style>
>    html { visibility: hidden; }
> <style>
> ```
> 
> And in the main CSS file I am using, set the visibility to `visible !important`. Similarly, you can use a `:global(html) { ... }` on your `__layout.svelte` for instance.

This seems like a pretty good temporary solution, but I hope this gets fixed in sveltekit as this "fix" would prevent all content from being shown if the CSS fails to download for some reason.

**Comment by OG84** [comment]
Yep i also get pretty bad flashes with chrome on production. I think because head elements are re–inserted or reordered after hydration.

**Comment by seanlail** [comment]
> I think because head elements are re–inserted or reordered after hydration.

Do we know where this is happening? 

Might not be related but, after updating to the latest Svelte dependency, my Sapper + Rollup app has an issue where every element in the head is reversed.

So this bug might not be related to Kit or Vite (if that assumption above is correct).

**Comment by OG84** [comment]
Right, this probably not related to kit.
See https://github.com/sveltejs/svelte/issues/6463 and https://github.com/sveltejs/svelte/pull/6449

**Comment by subhendupsingh** [comment]
> > Has anyone noticed this issue on prod? I am having some weird CSS flashes on refresh, even for a cached browser. Seems to happy mainly, if not only, on Chrome for Windows. Not sure if this is a Svelte issue or Chrome
> 
> I definitely have this issue on Brave (chromium) on MacOS as well. Mitigated it by setting the following style on the `app.html` .
> 
> ```
> <style>
>    html { visibility: hidden; }
> <style>
> ```
> 
> And in the main CSS file I am using, set the visibility to `visible !important`. Similarly, you can use a `:global(html) { ... }` on your `__layout.svelte` for instance.

Solution works! Does this in any way impact SEO?

**Comment by mhatvan** [comment]
I noticed this yesterday, FOUC occurs in Chromium based browsers but not Firefox for some reason.

**Comment by crinklesio** [comment]
> > > Has anyone noticed this issue on prod? I am having some weird CSS flashes on refresh, even for a cached browser. Seems to happy mainly, if not only, on Chrome for Windows. Not sure if this is a Svelte issue or Chrome
> > 
> > 
> > I definitely have this issue on Brave (chromium) on MacOS as well. Mitigated it by setting the following style on the `app.html` .
> > ```
> > <style>
> >    html { visibility: hidden; }
> > <style>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And in the main CSS file I am using, set the visibility to `visible !important`. Similarly, you can use a `:global(html) { ... }` on your `__layout.svelte` for instance.
> 
> Solution works! Does this in any way impact SEO?

As far as I could tell not. I am no SEO expert, but I did multiple lighthouse tests and did not see and impact on the performance or SEO scores when doing the tests before and after this fix, many times.

**Comment by benaltair** [comment]
After upgrading to the most recent `next` version of Kit, I get FOUC in prod. Here's an example:
https://60ed0aacdb48670007a2bce6--abs2021.netlify.app/

Try navigating to a number of pages - it seems to happen 1/3rd of the time or so. This did not happen before upgrading. 

Current version with issue:
```
		"@sveltejs/adapter-netlify": "^1.0.0-next.20",
		"@sveltejs/kit": "^1.0.0-next.125"
```

Previous version without issue:
```
		"@sveltejs/adapter-netlify": "next",
		"@sveltejs/kit": "^1.0.0-next.121"
```

**Comment by benmccann** [comment]
Hi all. This issue has been getting a lot of comments related to a bug in Svelte Core that was fixed in 3.40.0. I'm hiding many of the most recent comments as off-topic because they're unrelated to the original issue here

**Comment by jaintarun** [comment]
I am still having the FOUC issue on my site. Updated to latest svelte & sveltekit versions.
My symptoms though are that FOUC only flashes **once ** 
All subsequent pages are fine.

Any ideas why this might be still happening?

**Comment by mishrasatyam** [comment]
I am using svelte 3.42.1 and @sveltejs/kit 1.0.0-next.146  on a windows machine, I am only getting FOUC when I use __layout.reset.svelte

**Comment by FaberVitale** [comment]
I've got a similar issue with a [scss file](https://github.com/FaberVitale/about-my-device/blob/chore/svelte-kit/src/styles/app.scss) imported in [routes/__layout.svelte](https://github.com/FaberVitale/about-my-device/blob/chore/svelte-kit/src/routes/__layout.svelte#L3)

It seems that it does not load those styles in a render blocking manner. 
It is a bit jarring because it does not then happen on the bundled version.

[repo source](https://github.com/FaberVitale/about-my-device/tree/chore/svelte-kit)

### Dependencies

"@sveltejs/kit":  "1.0.0-next.158"
"@sveltejs/adapter-static": 1.0.0-next.17
"svelte": "3.42.4"
"svelte-preprocess": "4.8.0"
"vite": "2.5.1"
"sass": "1.38.2"

computer macOs Catalina
node v14.17.3

**Comment by brettgoulder** [comment]
I get issues with FOUC with the latest SvelteKit and TailwindCSS

- Create a brand new SvelteKit app skeleton
- Add `npx svelte-add@latest tailwindcss` 
- Add a class like "text-red-500" to an h1 and refresh

**Comment by jaintarun** [comment]
If it helps anyone.. i found that my FOUC was only happening when I had references to CSS in my app.html
When I moved the CSS ref to the layout file, the FOUC issue went away.

**Comment by Augustin82** [comment]
We have the same issue on our project. The CSS is not in the `app.html` file, but is imported in the `context` script in the root `__layout.svelte` file.

**Comment by bojanv55** [comment]
I have the same problem with latest svelte kit:

```
"@sveltejs/adapter-static": "^1.0.0-next.21",
    "@sveltejs/kit": "next",
    "@testing-library/jest-dom": "^5.15.0",
    "@testing-library/svelte": "^3.0.3",
    "@types/jest": "^27.0.2",
    "jest": "^27.3.1",
    "node-sass": "^6.0.1",
    "sass": "^1.43.3",
    "svelte": "^3.42.6",
    "svelte-check": "^2.2.6",
    "svelte-jester": "^2.1.5",
    "svelte-preprocess": "^4.9.4",
```

This is what I get:

![svelte-css](https://user-images.githubusercontent.com/1422698/140935766-9695c02f-c910-4e6d-aae4-651fc6c31332.gif)

What I notices is that `@include` in `global.scss` are properly rendered in `view-source`, but all other elements are rendered later. Also, when using `goto()`, `:global` style is not cleared from the previous page.

**Comment by abohannon** [comment]
I'm running into this issue, as well. Working off of the base SvelteKit project. When I rename `app.css` to `app.scss` and update the import in `__layout.svelte` I get FOUC in development. Doesn't happen in production or local build.

svelte.config.js
```
import preprocess from 'svelte-preprocess';
import vercel from '@sveltejs/adapter-vercel';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: preprocess({ postcss: true }),
	kit: {
		adapter: vercel(),

		// hydrate the <div id="svelte"> element in src/app.html
		target: '#svelte'
	}
};

export default config;
```

postcss.config.cjs
```
const autoprefixer = require('autoprefixer');

module.exports = {
	plugins: [autoprefixer]
};

```

**Comment by bmcilw1** [comment]
I get this issue as well

svelte.config.js
```js
import adapter from '@sveltejs/adapter-auto';
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  // Consult https://github.com/sveltejs/svelte-preprocess
  // for more information about preprocessors
  preprocess: [
    preprocess({
      postcss: true,
    }),
  ],

  kit: {
    adapter: adapter(),

    // hydrate the <div id="svelte"> element in src/app.html
    target: '#svelte',
  },
};

export default config;

```

postcss.config.cjs
```cjs
const tailwindcss = require('tailwindcss');
const autoprefixer = require('autoprefixer');
const cssnano = require('cssnano');

const mode = process.env.NODE_ENV;
const dev = mode === 'development';

const config = {
  plugins: [
    tailwindcss(), // first load TailwindCSS
    autoprefixer(), // then run autoprefixer
    !dev && // optimize the code for production
      cssnano({
        preset: 'default',
      }),
  ],
};

module.exports = config;

```

tailwind.config.cjs
```cjs
const config = {
  mode: 'jit',
  content: ['./src/**/*.{html,js,svelte,ts}'],
  theme: {
    extend: {},
  },
  // Only add this if you installed the TailwindCSS-plugins:
  plugins: [require('@tailwindcss/typography'), require('@tailwindcss/forms')],
};

module.exports = config;
```

index.svelte
```svelte
<script>
  // src/routes/__layout.svelte
  import "../app.pcss";
</script>

<h1>Welcome to SvelteKit</h1>
<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>
```

**Comment by TheophileMot** [comment]
I have this problem as well, in both development and production. I'm using Tailwind and Carbon components (which requires SCSS).

![Jan-26-2022 09-32-54](https://user-images.githubusercontent.com/34871447/151190429-2f753815-ef97-4376-9934-574db0915504.gif)

**Comment by timwis** [comment]
I'm experiencing this issue on a fresh sveltekit project after installing `npx svelte-add@latest bulma`

**Comment by skrenes** [comment]
I found the [answer](https://stackoverflow.com/a/70723469) everyone! Give that person a thumbs up! No need to modify your `svelte.config.js` file either. Basically instead of importing the scss file at the top of `__layout.svelte`, remove that and instead add the style with the defined language and `global` keyword. The `global` keyword is the secret sauce to ensure it's not locally scoped.

More explicitly, remove this from the top of `__layout.svelte`:
```js
import '../app.scss';
```
And add this to the bottom:
```svelte
<style lang="scss" global>
  @import '../app.scss';
</style>
```

**Comment by timwis** [comment]
@skrenes that did it—thanks!

Only thing is it threw an error that I can only have one top-level `<style>` component (I had another non-global one for my layout's actual styles). I moved these styles inside the `global` one to fix it, though that feels like a bit of a workaround. I guess it's no difference since it's the root layout anyway?

**Comment by skrenes** [comment]
Yeah, I guess while it feels dirty polluting the global styles, `__layout.svelete` is always the top-level component, so semantically it's the same thing. But I'm not an authority on SvelteKit best practice, so perhaps someone else has a better way.

**Comment by joshpierce** [comment]
So if anyone else comes across this issue while using __layout.reset.svelte it's important to **import '../app.css'** (or in my case in a subfolder import '../../app.css'; however nested your layout reset might be) in your layout reset component. I had created this layout from scratch and hadn't included that so I was getting a nasty FOUC. 😅

**Comment by Rich-Harris** [comment]
Alright, I figured out what's going on here. Turns out I even anticipated this bug and added a TODO at some point:

https://github.com/sveltejs/kit/blob/623fa495c46e22213185199e56fad5a3fbaa2f80/packages/kit/src/core/dev/plugin.js#L82-L86

The easy fix would be to just add `.scss` and whatever else to the list of extensions it recognises, though that feels like a bit of a kludge. Open to any other bright ideas about how to identify that Vite is treating a module as CSS!

**Comment by bluwy** [comment]
Vite has a [hardcoded list](https://github.com/vitejs/vite/blob/3edd1af56e980aef56641a5a51cf2932bb580d41/packages/vite/src/node/plugins/css.ts#L96) of CSS langs too. There isn't an API or trick to share the code from Vite, so a compromise now is to copy it over.

**Comment by tcc-sejohnson** [comment]
I can't think of a better solution than hardcoding the CSS variants in. Given that the smart people over at Vite haven't come up with anything either, I think it may be the best choice. One possibility would be to hardcode our list here, leaving a TODO to revisit it occasionally to see if there's a better way -- better to provide a stable fix now (I mean, really, how often is there a new CSS filetype variant) and perhaps revisit later...

If we want to go with the hardcoded approach, I can work up a pull request.

**Comment by gaarf** [comment]
I didn't have the flash of unstyled in dev before https://github.com/sveltejs/kit/pull/4882, but now I do :-(

**Comment by benmccann** [comment]
@gaarf can you file a new issue with steps to reproduce and then link to it from here? We'd need more info...

**Comment by Conduitry** [comment]
It sounds like the regression may have been #4987 and would be fixed by #4990.

**Comment by gaarf** [comment]
@benmccann @Conduitry after cleaning build and updating to `@sveltejs/kit@1.0.0-next.336`, things are working as expected, no more flash in dev 🥳
