### ISSUE TITLE
ssr: false - Breaks all styling

### ISSUE THREAD

**Issue by jcbcn** [sveltejs/kit#924]
**Describe the bug**
Styling seems to break when `npm run build && npm start` with `ssr: false`.

`npm start dev` appears to be fine.

**To Reproduce**
`npm init svelte@next`
`ssr: false` in svelte.config.cjs
`npm run build && npm start`

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`
```
  System:
    OS: macOS 11.2.2
    CPU: (8) arm64 Apple M1
    Memory: 373.28 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.12.0 - /opt/homebrew/bin/node
    npm: 7.6.3 - /opt/homebrew/bin/npm
  Browsers:
    Firefox: 87.0
    Safari: 14.0.3
    Safari Technology Preview: 14.2
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.71 
    svelte: ^3.29.0 => 3.37.0 
    vite: ^2.1.0 => 2.1.5 
```
- Your browser
Firefox
- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
Tested on node & static
</details>

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of SvelteKit entirely?

Production builds appear to be blocked for users not using ssr

**Comment by henryenth** [comment]
css is not being compiled using vite plugins either seems to be completely ignored with ssr set to false

**Comment by mattiash** [comment]
I have the same issue with all styles disappearing with ssr: false. Rolling back to kit 1.0.0-next.65 made styles appear again.

**Comment by jcbcn** [comment]
Thanks @mattiash, can confirm rolling back to `1.0.0-next.65` has worked as a temporary fix for me as well.

**Comment by mattiash** [comment]
Works again for me `1.0.0-next.77`. Maybe fixed by PR #1053?

**Comment by frederikhors** [comment]
It still doesn't work to me, @mattiash. 

The file `build/app/assets/pages/$layout.svelte-5b7ff615.css` doesn't get called.

I get only the `start-0826e215.css` one.

**Comment by mattiash** [comment]
@frederikhors interesting. My playground code here https://github.com/mattiash/svelte-admin-ui/ (deployed here when I push to master: https://admiring-hugle-f8c3a4.netlify.app/ ) started working when I upgraded to .77.

**Comment by frederikhors** [comment]
@mattiash thanks for your hint.

I tried your source code, latest commit, npm install, npm run build, http-server: it doesn't work.

If you search in all the `build` dir for `$layout.svelte-310bc114.css` you find nothing.

Are you sure that link is not for `v65`?

**Comment by mattiash** [comment]
I just ran the following command: 

```
git clone https://github.com/mattiash/svelte-admin-ui.git; cd svelte-admin-ui; npm install; npm run build; cd build; npx serve .
```

Opening http://localhost:5000 in a results in a webpage with proper css styling.

If I then do

```
cd ..; npm install @sveltejs/kit@1.0.0-next.71; npm run build; cd build; npx serve .
```

I get a webpage without styling. So for me, .77 works but .71 doesn't.

**Comment by frederikhors** [comment]
After your steps this is my situation:

![image](https://user-images.githubusercontent.com/41120635/115118496-b29c3780-9fa3-11eb-8ca9-e75de7917695.png)

```
  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 7.10.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @sveltejs/kit: 1.0.0-next.65 => 1.0.0-next.65
    svelte: 3.37.0 => 3.37.0
    vite: 2.1.5 => 2.1.5
```

**Comment by frederikhors** [comment]
I am trying to block dependency versions now.

**Comment by mattiash** [comment]
```
npx: installed 1 in 0.991s

  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Apple M1
    Memory: 25.74 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Firefox: 88.0
    Safari: 14.0.3
  npmPackages:
    @sveltejs/kit: 1.0.0-next.77 => 1.0.0-next.77
    svelte: ^3.37.0 => 3.37.0
    vite: ^2.1.5 => 2.1.5
```

**Comment by frederikhors** [comment]
It doesn't work to me even with highest deps and `rm -rf node_modules`.

Can you try with npm 7?

**Comment by mattiash** [comment]
I made some more experiments by building in a clean docker container. For me it is 100% reproducible. With `1.0.0-next.77`, the styling looks good, with `1.0.0-next.71` the page is unstyled. I ran the test in the docker container `node:14.16.1-buster` with both the default npm (v6) and with npm `7.10.0`.

**Comment by frederikhors** [comment]
Wow. This is nonsense. I'm cloning in a clean dir. The only difference now is Windows 10?

**Comment by mattiash** [comment]
Maybe related to issue #606?

**Comment by frederikhors** [comment]
Maybe, yes.

**Comment by frederikhors** [comment]
It works today with 79. I think we can close this, @mattiash.

**Comment by mattiash** [comment]
I agree. I tested with .80 and it works for me as well.

**Comment by babichjacob** [comment]
Closing because it's reportedly fixed, possibly by https://github.com/sveltejs/kit/pull/1053?
If it's still reproducible on latest versions of all packages (`@sveltejs/kit` `1.0.0-next.80` or newer), please @ping **me** and I'll re-open this.
