### ISSUE TITLE
"500 Internal Error" in Vercel.

### ISSUE THREAD

**Issue by engageintellect** [sveltejs/kit#9967]
### Describe the bug

I have a basic Sveltekit app using Pocketbase as a backend/db. I am using form actions to register and login users, which seems to be working ok.

However, when trying to load data from pocketbase using +page.svelte/+page.ts and the load function, everything works perfectly in a dev server, but throws "500 Internal Error" when deployed to Vercel

Here is the code to +page.svelte and +page.ts
![image](https://github.com/sveltejs/kit/assets/61082194/6d34ec3e-6ab2-4d62-8922-248f899dba71)

On the left is the dev server, on the right is Vercel (prod), before user is logged in:
![image](https://github.com/sveltejs/kit/assets/61082194/c51a862c-5e46-4613-8c18-b2dbe6712954)

Now, after being logged in:
![image](https://github.com/sveltejs/kit/assets/61082194/5de8dfdb-28ae-4a4e-b0db-5a5827948b4f)

Not sure what I'm missing here... Hopefully someone can break it down for me. I don't understand why I would have an error before the user is logged in (when the "else" on my if/else conditioned is being met)

Vercel Logs:
![image](https://github.com/sveltejs/kit/assets/61082194/f9344484-6f92-4329-8fe8-3a20bbdf5043)

### Reproduction

You likely won't be able to reproduce, as the pocketbase db is on my personal linode server. However, here is the code: https://github.com/engageintellect/sveltekit-auth-pocketbase

* clone repo
* pnpm i && pnpm run dev (everything works)
* push/deploy to vercel (user register/login works, data fetching doesn't)

### Logs

```Shell
It doesn't even look like my load function is running in the vercel logs, I just see the logout and login endpoints (photo in description above)
```

### System Info

```Shell
System:
    OS: Linux 5.10 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 3.61 GB / 7.72 GB
    Container: Yes
    Shell: 3.1.0 - /usr/bin/fish
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.2.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.3 
    @sveltejs/kit: ^1.15.2 => 1.16.3 
    svelte: ^3.54.0 => 3.59.1 
    vite: ^4.0.0 => 4.3.7
```

### Severity

blocking all usage of SvelteKit

**Comment by gtm-nayan** [comment]
> You won't be able to reproduce, as the pocketbase db is on my private server.

If you had read the issue template, you'd have seen that we cannot help you without a proper reproduction. But, I'm going to hazard a guess that your pocketbase db is indeed so private that even Vercel's servers can't access it and that's the error.

**Comment by engageintellect** [comment]
> 

Then how would I be able to register and login new users in the pocketbase instance on the server?

Updating reproduction steps...

**Comment by tcc-sejohnson** [comment]
Are you deploying to edge or lambda? If edge, it's possible you're using an unsupported API.

**Comment by engageintellect** [comment]
> Are you deploying to edge or lambda? If edge, it's possible you're using an unsupported API.

I'm assuming lambda, as I haven't explicitly specified or changes anything in the svelte config. Using adapter-auto.

**Comment by engageintellect** [comment]
Just noticed I am getting this error in the browser console:

```
Blocked loading mixed active content
```

**Comment by tcc-sejohnson** [comment]
I noticed your lockfile is on v15.x; try upgrading. We fixed a cookie bug having to do with `httpOnly` in v16.x (iirc) and my gut tells me there's a nonzero chance it'll fix this issue

**Comment by engageintellect** [comment]
Great catch. However, I just updated Sveltekit to "latest" (1.18), and the problem still persist.

```
  System:
    OS: Linux 5.10 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 4.83 GB / 7.72 GB
    Container: Yes
    Shell: 3.1.0 - /usr/bin/fish
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.2.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.3 
    @sveltejs/kit: latest => 1.18.0 
    svelte: ^3.54.0 => 3.59.1 
    vite: ^4.0.0 => 4.3.7 
```


Also, here is the browser console output I am getting:
```
Blocked loading mixed active content “http://<MY_POCKETBASE_IP>:8090/api/collections/albums/records?page=1&perPage=200&sort=-created”
```

Any other ideas? Or things I should try? I'm not using https on Pocketbase, though I don't think it matters as registering and logging in users still works fine... as well as adding entries to the table I am trying to fetch/display 🤔

Thanks!

**Comment by gtm-nayan** [comment]
> though I don't think it matters as registering and logging in users still works fine... as well as adding entries to the table I am trying to fetch/display

all of those happen on the server where it doesn't really care that you're using http, the browser, where you fetch the data in +page.ts, does care

**Comment by engageintellect** [comment]
Ahhh, this was totally helpful. So, here is what I did to get it working...

Instead of exporting a load function in +page.ts, I made a /routes/getRecords/+server.ts endpoint, which seems to work perfectly on vercel. https://sveltekit-auth-pocketbase-4cj86xd6l-engageintellect.vercel.app/

Now I just have to figure out how to go about deleting items, and passing the "id" prop from my card component to /routes/deleteRecord/+server.ts. Not sure if there is a "right" way to do this, I suppose my first thought would be to just use a store? 🤔

Anyhow, thank you very much for your guidance. You helped get me back on track. @gtm-nayan
